apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: fluentd-cloudwatch-{{ .Release.Name }}
data:
{{ toYaml .Values.configMapData | indent 2 }}
